export default {
   // SETS
   TOGGLE_SET: "TOGGLE_SET",
   ADD_SET: "ADD_SET",
   REMOVE_SET: "REMOVE_SET",


   // FILTER
   SET_VISIBILITY_FILTER: "SET_VISIBILITY_FILTER",
   SHOW_ALL: "SHOW_ALL",
   SHOW_ACTIVE: "SHOW_ACTIVE",
   SHOW_COMPLETED: "SHOW_COMPLETED",


   // STOPWATCH
   START_STOPWATCH: "START_STOPWATCH",
   STOP_STOPWATCH: "STOP_STOPWATCH",
   INCREMENT_STOPWATCH: "INCREMENT_STOPWATCH",
   RESET_STOPWATCH: "RESET_STOPWATCH"  
}